import type { Frame, Skin } from './types';
import { y2k } from './y2k';

// «Олег XP»: Windows XP Luna — blue title bars, beige windows, the green «пуск»
// button and the «Безмятежность» hill behind everything. No Claude Design mockup:
// colours are the stock Luna palette.
const ink = '#000000';
const luna = { grad: ['#3A8CF7', '#0A50D8'] as const, text: '#FFFFFF' };
const start = { grad: ['#4FBF4F', '#2D8F2D'] as const, text: '#FFFFFF' };
const button = { grad: ['#FFFFFF', '#E3E0D3'] as const, text: ink };

const window: Frame = { borderWidth: 1, borderColor: '#0A3FAE', boxShadow: '2px 3px 8px rgba(0,0,0,0.35)' };
const field: Frame = { borderWidth: 1, borderColor: '#7F9DB9', boxShadow: 'none' };

export const xp: Skin = {
  id: 'xp',
  name: 'Олег XP',
  dark: false,
  shape: { kind: 'luna', maxRadius: 8 },
  frames: {
    card: window,
    field,
    panel: { borderWidth: 1, borderColor: '#0A3FAE' },
    button: { borderWidth: 1, borderColor: '#003C74' },
  },
  colors: {
    ...y2k.colors,
    ink,
    text2: '#3B3B3B',
    text3: '#555555',
    text4: '#6F6F6F',
    placeholder: '#8A8A8A',
    accentText: '#0A50D8',
    nameText: '#0B2E8A',
    focus: '#316AC5',
    focusGlow: 'rgba(49,106,197,0.25)',
    voteTitle: '#FFFFFF',
    labelText: '#0B2E8A',
    serviceText: '#000000',
    serviceBg: '#FFFFE1',
    neon: '#3FBF3F',
    neonGlow: 'rgba(63,191,63,0.6)',
    voteNo: '#E0412B',
    danger: '#C1311B',
    dangerText: '#A0200C',
    dangerBg: '#FFF2EE',
    dangerBorder: '#E0412B',
    okBg: '#EDFBE9',
    okBorder: '#3FBF3F',
    limeAccent: '#2D8F2D',
    chromeEdge: '#0A3FAE',
    chromeInk: '#FFFFFF',
    lcdBg: '#FFFFFF',
    lcdText: '#0A50D8',
    led: '#3FBF3F',
    readTick: '#0A50D8',
    screen: '#ECE9D8',
    surface: '#ECE9D8',
    surfaceBorder: '#0A3FAE',
    field: '#FFFFFF',
    fieldText: ink,
    fieldFocus: '#FFFFFF',
    fieldBorder: '#7F9DB9',
    fieldBorderSoft: '#A5B9CF',
    sidebar: '#F4F2E8',
    divider: '#C9C5B2',
  },
  roles: {
    cta: start,
    action: luna,
    round: start,
    chipNew: luna,
    chipInvite: { grad: ['#F7B54A', '#E07B00'], text: '#FFFFFF' },
    chipGroup: start,
    positive: start,
    negative: button,
    danger: { grad: ['#F07A62', '#C1311B'], text: '#FFFFFF' },
    badge: { grad: ['#F07A62', '#C1311B'], text: '#FFFFFF' },
    selected: { grad: ['#316AC5', '#316AC5'], text: '#FFFFFF' },
    tab: luna,
    vote: luna,
    promo: { grad: ['#FFFFE1', '#FFF6B8'], text: ink },
  },
  bubbles: {
    theirs: { grad: ['#FFFFFF', '#FFFFFF'], text: ink, meta: '#6F6F6F', border: '#A5B9CF' },
    mine: { grad: ['#E3EEFF', '#C9DCFB'], text: ink, meta: '#3B5F99', border: '#7FA2DD' },
    shine: false,
  },
  ball: ['rgba(58,140,247,0.85)', 'rgba(10,80,216,0.95)'],
  stickerAvatar: ['#FFFFFF', '#D6E4F7'],
  chrome: {
    colors: ['#3D95FF', '#0A64E8', '#0553D4', '#0A5BE0', '#1F6FF0'],
    locations: [0, 0.1, 0.5, 0.9, 1],
  },
  logoChrome: [
    { offset: 0, color: '#FFFFFF' },
    { offset: 0.5, color: '#E8F0FF' },
    { offset: 1, color: '#BFD3FF' },
  ],
  logoShadow: '#0A3FAE',
  hero: 'ball',
  authPanel: true,
  background: { kind: 'bliss', gradient: ['#2E6FE0', '#A8D0F5'], line: '#4E9A2A' },
  avatars: [
    ['#3A8CF7', '#0A50D8'],
    ['#4FBF4F', '#2D8F2D'],
    ['#F7B54A', '#E07B00'],
    ['#F07A62', '#C1311B'],
    ['#B48CF0', '#6A3FC8'],
  ],
  authorColors: ['#0A50D8', '#2D8F2D', '#C1311B', '#B05A00', '#6A3FC8'],
  fonts: {
    display: 'PTSans_700Bold',
    body: 'PTSans_400Regular',
    bodyBold: 'PTSans_700Bold',
    bodyHeavy: 'PTSans_700Bold',
    mono: 'PTMono_400Regular',
    field: 'PTSans_400Regular',
  },
  vote: { meta: 'body', bar: 'smooth', buttonFont: 'bodyHeavy' },
  copy: {
    ...y2k.copy,
    loginButton: 'Вход в систему',
    registerButton: 'Установить Олега',
    footer: 'ЛИЦЕНЗИЯ: ОЛЕГ ПРОФЕССИОНАЛЬНЫЙ · КЛЮЧ НЕ НУЖЕН',
    noSignal: 'Подключение к сети отсутствует. Кабель не подключён.',
    errorPrefix: 'Олег XP — ошибка:',
    loginError: 'Программа выполнила недопустимую операцию и будет закрыта. Проверьте ник и пароль.',
    search: 'Найти файлы и папки…',
    newChat: '+ Новое окно',
    composer: 'Введите сообщение…',
    send: 'Отправить',
    typing: 'печатает…',
    online: 'в сети',
    offline: 'не в сети',
    ticks: ['Отправлено', 'Доставлено', 'Сохранено в «Мои документы»'],
    emptyFeed: 'Папка пуста. Отправьте первое сообщение.',
    voteTitle: 'Обнаружено новое устройство!',
    voteFor: 'Разрешить',
    voteAgainst: 'Отмена',
    settings: 'Панель управления',
  },
};
